### PR TITLE
Try adding macOS to CI

### PR DESCRIPTION
**Pull request by armanbilge**

### CODE REVIEW

**Comment by armanbilge** [comment]
```
dyld: lazy symbol binding failed: Symbol not found: _curl_multi_poll
  Referenced from: /Users/runner/work/http4s-curl/http4s-curl/curl/target/scala-3.1.3/http4s-curl-test-out
  Expected in: /usr/lib/libcurl.4.dylib

dyld: Symbol not found: _curl_multi_poll
  Referenced from: /Users/runner/work/http4s-curl/http4s-curl/curl/target/scala-3.1.3/http4s-curl-test-out
  Expected in: /usr/lib/libcurl.4.dylib
```

macOS is not my daily driver. Help wanted! :)

**Comment by armanbilge** [comment]
Relevant? https://developer.apple.com/forums/thread/672026

**Comment by LeeTibbert** [comment]
I used "brew install curl" and got a full, working link.  

The .yml has a section to install libcur4-openssl-dev on linux
I think it needs a section for macos which does the "brew'ing above.

**Comment by LeeTibbert** [comment]
FYI,
When I clone the repository into a fresh directory, macOS 12.5 M1 and "sbt test"
I get the failure `curl_easy_setop: 1` twice, once for `get` and once for `post`.

Perhaps http4s does not like the Southern heat?

So, no magical cures to building.

I can try an example program which uses the published
artifacts, either/both macOS (M1)  & Ubuntu 22.04 (X86_64).

If those work, then the Issue of building falls to a (vanishingly) low priority.

**Comment by armanbilge** [comment]
That's bizarre.
```
CURLE_UNSUPPORTED_PROTOCOL (1)

The URL you passed to libcurl used a protocol that this libcurl does not support. The support might be a compile-time option that you did not use, it can be a misspelled protocol string or just a protocol libcurl has no code for.
```

https://curl.se/libcurl/c/libcurl-errors.html

Let's see what CI things of brew :)

**Comment by armanbilge** [comment]
Sadly, the `brew install curl` results in the same error. Indeed, seems that curl is already installed via brew 😂 

```
Run brew install curl
  brew install curl
  shell: /bin/bash -e {0}
  env:
    PGP_PASSPHRASE: 
    SONATYPE_PASSWORD: ***
    SONATYPE_CREDENTIAL_HOST: 
    SONATYPE_USERNAME: ***
    PGP_SECRET: ***
  
    GITHUB_TOKEN: ***
    JAVA_HOME: /Users/runner/hostedtoolcache/Java_jdkfile_jdk/17/x64/Contents/Home
  
Warning: curl 7.84.0 is already installed and up-to-date.
To reinstall 7.84.0, run:
  brew reinstall curl
```

**Comment by LeeTibbert** [comment]
I do not understand, if curl was installed, why did your first pass not find the .dynlib?  Arrgh.

So, I suggest a section in the README saying "Artifacts only", so the eager people have
some idea of where the edge of the world is.

So many bugs, so little time.

**Comment by armanbilge** [comment]
`brew info curl` tells me the following:
```
==> Caveats
curl is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have curl first in your PATH, run:
  echo 'export PATH="/usr/local/opt/curl/bin:$PATH"' >> /Users/armanbilge/.bash_profile

For compilers to find curl you may need to set:
  export LDFLAGS="-L/usr/local/opt/curl/lib"
  export CPPFLAGS="-I/usr/local/opt/curl/include"

For pkg-config to find curl you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"
```

Perhaps you have some special configuration on your local?

**Comment by LeeTibbert** [comment]
As per brew instructions
```
  export LDFLAGS="-L/usr/local/opt/curl/lib"
  export CPPFLAGS="-I/usr/local/opt/curl/include"
```

**Comment by LeeTibbert** [comment]
Sorry for the misinformation about FLAGS. I did a cut & paste of the 
post above it and got it wrong.

I ought to be able to get over this, but it gnaws on me.

I am going to fork this repository and so that I can thrash
on the mac build without sucking up the time of other people.

```
export LDFLAGS="-L/opt/homebrew/opt/curl/lib"
 export CPPFLAGS="-I/opt/homebrew/opt/curl/include"
```

CI here is running macOS 11.mumble and my system is at 12.5,
so world apart.

**Comment by LeeTibbert** [comment]
I think there is a life lesson in here somewhere.  So much effort leading to victory where that victory itself
is a failure.

A cleaned up and scalaformat'ed version of this edit to `build.sbt` gets http4s-curl working on macOS CI
in my fork of this project.  A warning, it is not pretty so people of wisdom or tender sensibilities should
look away now:
```
ThisBuild / nativeConfig ~= { c => {
    val osName = System.getProperty("os.name")
    val isMacOs = osName.toLowerCase().startsWith("mac os x")
    if (!isMacOs) {
      c // do not change                                                        
    } else {
         c.withLinkingOptions(c.linkingOptions ++ Seq(
                            "-L/usr/local/Cellar/curl/7.84.0/lib"))
    }
  }
}

```
Someone with a better knowledge of sbt, or myself after I have had a rest, could probably
make that less ugly.

The whole `curl/7.84.0` business seems incredibly likely to break over time.
At least it works today, which has another 3 minutes to go.

With this & no changes to `ci.yml` (no additional environment variables), http4s-curl
test links & runs on both GitHub mac-latest (11.mumble) and mac-12 (Monterry-mumble).

That is the victory part which gets to both/all failing with `curl_easy_pause: 43` in two places
each: get & post.  

At least now we know.  CI is doing its job

**Comment by armanbilge** [comment]
Thanks! Actually this is a big help. It seems that there was a change in modern libcurl that is causing the `curl_easy_pause: 43` error. Now that we can replicate the issue on both macOS and ubuntu it will hopefully make it easier to solve (or find someone to solve it :)

**Comment by armanbilge** [comment]
I was able to get it running on my local macOS with this snippet:
```scala
ThisBuild / nativeConfig ~= { c =>
  val osName = Option(System.getProperty("os.name"))
  val isMacOs = osName.exists(_.toLowerCase().contains("mac"))
  if (isMacOs) { // brew-installed curl
    c.withLinkingOptions(c.linkingOptions :+ "-L/usr/local/opt/curl/lib")
  } else c
}
```

All that's left now is to fix https://github.com/http4s/http4s-curl/issues/6 😂

**Pull request merged**
